include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - example/**
    - test/**
    - bin/**
    - extension/**
    - native_workmanager_gen/**

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - avoid_void_async
    - unawaited_futures
    - always_declare_return_types
    - avoid_relative_lib_imports
